### ISSUE TITLE
[bug]Error when cleanup MaaAssistantArknights

### ISSUE THREAD

**Issue by eidswe** [Darkatse/Scoop-Darkatse#7]
scoop cleanup MaaAssistantArknights
Removing MaaAssistantArknights: 4.10.4Get-Item: C:\Users\eidswe\scoop\apps\scoop\current\lib\install.ps1:1182
Line |
1182 |              $source = Get-Item "$dir\$source"
     |                        ~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\eidswe\scoop\apps\MaaAssistantArknights\4.10.4\map' because it does not exist.
Get-Item: C:\Users\eidswe\scoop\apps\scoop\current\lib\install.ps1:1182
Line |
1182 |              $source = Get-Item "$dir\$source"
     |                        ~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\eidswe\scoop\apps\MaaAssistantArknights\4.10.4\gui.json' because it does not exist.
Remove-Item: C:\Users\eidswe\scoop\apps\scoop\current\libexec\scoop-cleanup.ps1:50
Line |
  50 |          Remove-Item $dir -ErrorAction Stop -Recurse -Force
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot remove item C:\Users\eidswe\scoop\apps\MaaAssistantArknights\4.10.4\debug\map: Access to the path
     | 'C:\Users\eidswe\scoop\apps\MaaAssistantArknights\4.10.4\debug\map' is denied.

**Comment by Darkatse** [comment]
已修复，以后的版本应该能正常清理。目前的版本需要到%USERPROFILE%/scoop/apps/MaaAssistantArknights/手动删除，记得保留一个最新的4.10.X不要删除。

**Comment by Darkatse** [comment]
或者也可以卸载后重装一次，保留MaaAssistantArknights/config/gui.json即可保留之前的设置
